Repository abhijeetnishal/Password-Shield, pull requests merged in 2024-06, with the labels that each got.

#102 [FEAT]:Add search functionally and resolve conflict
  server/src/controllers/password.ts
Labels: gssoc, level1

#89 Redesigned UI
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/public/assets/Illustration-1-dark.svg
  client/public/assets/Illustration-1.svg
  client/public/assets/Illustration-2-dark.svg
  client/public/assets/Illustration-2.svg
  client/public/assets/Illustration3.png
  client/public/assets/Login.svg
  client/public/assets/Ribbon-1.png
  client/public/assets/icon1.svg
  client/public/assets/icon2.svg
  client/public/assets/icon3.svg
  client/public/assets/icon4.svg
  client/public/assets/icon5.svg
  client/src/app/auth/login/page.tsx
  client/src/app/auth/register/page.tsx
  client/src/app/dashboard/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Headers/Navbar.tsx
  client/src/components/Icons/Dark.tsx
  client/src/components/Icons/Github.tsx
  client/src/components/Icons/Illustration1.tsx
  client/src/components/Icons/Illustration1dark.tsx
  client/src/components/Icons/Illustration2.tsx
  client/src/components/Icons/Illustration2dark.tsx
  client/src/components/Icons/IllustrationIcon.tsx
  client/src/components/Icons/LinkedIn.tsx
  client/src/components/Icons/LoginSvg.tsx
  client/src/components/Icons/icon1.tsx
  client/src/components/Icons/icon2.tsx
  client/src/components/Icons/icon3.tsx
  client/src/components/Icons/icon4.tsx
  client/src/components/Icons/icon5.tsx
  client/src/components/Icons/light.tsx
  client/src/store/themeStore.ts
  client/src/store/titleStore.ts
  client/tailwind.config.ts
Labels: enhancement, gssoc, level2

#115 [Feat] Redesign dashboard page
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/public/assets/Illustration3.png
  client/public/assets/Login.svg
  client/public/assets/Ribbon-1.png
  client/src/app/auth/login/page.tsx
  client/src/app/dashboard/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Headers/AuthHeader.tsx
  client/src/components/Headers/AuthNavbar.tsx
  client/src/components/Headers/Navbar.tsx
  client/src/components/Icons/Dark.tsx
  client/src/components/Icons/Github.tsx
  client/src/components/Icons/Icon1.tsx
  client/src/components/Icons/Icon2.tsx
  client/src/components/Icons/Icon3.tsx
  client/src/components/Icons/Icon4.tsx
  client/src/components/Icons/Icon5.tsx
  client/src/components/Icons/Illustration1.tsx
  client/src/components/Icons/Illustration1dark.tsx
  client/src/components/Icons/Illustration2.tsx
  client/src/components/Icons/Illustration2dark.tsx
  client/src/components/Icons/IllustrationIcon.tsx
  client/src/components/Icons/Light.tsx
  client/src/components/Icons/LinkedIn.tsx
  client/src/components/Icons/LoginSvg.tsx
  client/src/components/Icons/SiteIcon.tsx
  client/src/components/Loaders/LoadingSpinner/index.tsx
  client/src/components/Passwords/CreatePassword.tsx
  client/src/components/Passwords/DeleteConfirmation.tsx
  client/src/components/Passwords/EditPassword.tsx
  client/src/components/Passwords/Items.tsx
  client/src/components/Passwords/PasswordItem.tsx
  client/src/components/Passwords/PasswordStrength.tsx
  client/src/store/themeStore.ts
Labels: gssoc, level2

#126 feat:Implement reset password
  client/src/app/auth/forgot-password/page.tsx
  client/src/app/auth/login/page.tsx
  client/src/app/auth/register/page.tsx
  client/src/app/auth/reset-password/page.tsx
  client/src/services/AuthService/index.ts
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/config/dbConnect.ts
  server/src/controllers/auth.ts
  server/src/routers/auth.ts
  server/src/utils/auth.ts
Labels: gssoc, level2
