Repository abhijeetnishal/Password-Shield, pull requests merged in 2024-05, with the labels that each got.

#13 Add Learn.md file
  Learn.md
Labels: documentation

#15 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#41 Old data while editing bug fixed
  client/src/components/main/EditPassword.jsx
  client/src/components/main/PasswordPage.jsx
  client/src/styles/EditPassword.css
Labels: gssoc, level1

#60 Feat: Favicon Created.
  client/public/favicon.ico
  client/public/index.html
  server/src/index.ts
Labels: gssoc
